### PR TITLE
Replace in-tree libgd with external build of recent code

### PR DESCRIPTION
**Pull request by ErwinJanssen**
What I did:
- Added current source of libgd as a submodule in windows/dependencies.
- Added automated build rules of this code to Appveyor.
- Removed all files in lib/gd
- Changed include directory and library path where needed.
- Removed reference to lib/gd everywhere else.
- Removed two `extern`s in gvrender_gd.c

So the code now builds with a recent version of libgd that is not included in the source tree.

### CODE REVIEW

**Comment by ellson** [comment]
Many thanks for doing this.

**Comment by ErwinJanssen** [comment]
You're welcome, glad to help :)

**Comment by ErwinJanssen** [comment]
Are there more libraries like this? Code that is included in the repository that is either obsolete or outdated? For example I noticed that lib/agraph and lib/agutil are both never build or referenced anywhere in the code.
Maybe I could see what else there is present in the repository that could be removed.

**Comment by emden** [comment]
In terms of code in lib/, graph was the original graph library, which was replaced by agraph, which was replaced by cgraph. agutil looks like the start of an attribute handling utility library for agraph. inkpot was another library started by John to pull together all the various color handling code. dotgen2 is the sandbox where Stephen and I played with re-writing dot. Finally, spine contains a code for a recent algorithm to help untangle hairballs. Since none of these get built or distributed in source, they shouldn't be problem. In my opinion, I could see removing agraph, graph and agutil, and I would definitely keep dotgen2 and spine. But definitely check with John and Stephen.

**Comment by ellson** [comment]
Erwin,

lib/agraph  et.al.  is code that we wrote, but that isn't used. We keep 
it more for reference.

lib/inkpot is code I was working on but never completed

lib/gd, and lib/rxspencer, are not our code.  So they are a different 
animal.  Including them in our tree is effectively a fork of someone 
else's code and it puts us in the position of needing to support the fork.

I feel that the tree is clean enough at this point.


Its a bit of a new practice for everyone to be cloning directly from the 
primary repo, and so gaining visibility of all the unused bits.

In the old world, repos were typically private, and the practice was to 
build a portable source distribution, and publish that,  as in:

http://graphviz.org/pub/graphviz/development/SOURCES/graphviz-2.39.20160710.1729.tar.gz

In fact, all of our the RedHat builds still use this as their starting 
point.  The src.rpm is generated with:

     rpmbuild -ts graphviz-2.39.20160710.1729.tar.gz


The tar.gz  source distribution does not contain the unused bits from 
the repo,  and simplifies the toolchain requirements for the user by pre 
running autogen.sh, and by generating any portable products,  like pdf 
docs and yacc/lex products.

On Linux,  the traditional process of building from source is still 
supported:

     wget 
http://graphviz.org/pub/graphviz/development/SOURCES/graphviz-2.39.20160710.1729.tar.gz
     tar xzf graphviz-2.39.20160710.1729.tar.gz
     cd graphviz-2.39.20160710.1729
     ./configure
     make
     sudo make install

It would be nice, IMHO, if the Windows build could be generated from the 
same tar.gz,  but this is not a priority for me any more.   The git 
submodules seem to be working well for you,  but I don't want to ship 
submodule code (belonging to other projects) in a tar.gz.  So better to 
use GIT and have the user pull the submodules directly.


John

**Comment by ErwinJanssen** [comment]
Thank you for your extensive answers. I understand that the new way of working "out in the open" is different and takes time getting used to. I'm not trying to impose a new way of working, but I try to gain a deeper understanding of how this software works, how the code is structured and what could be improved.

My suggestion in this area is added a README to every subproject, so it becomes more clear which parts are still used, which exist as a reference and which are a work in progress. Also the purpose and functionality of the subproject could become more clear this way. This is something I can't do, because you are way more familiar with the software and the codebase, but let me know if I can help.

**Pull request merged**
