### PR TITLE
WIP: AppVeyor

### PR DESCRIPTION
**Pull request by tkelman**
Based on the steps in #36, this will need to download some things into release ahead of time. I'm not sure where to get those from. Here's a log of what this looks like so far:

https://ci.appveyor.com/project/tkelman/graphviz/build/1.0.6

### CODE REVIEW

**Comment by tkelman** [comment]
I'm not really a visual studio person. I have no idea what
```
Microsoft (R) Visual Studio Version 9.0.30729.1.
Copyright (C) Microsoft Corp. All rights reserved. 
 
'c:\graphviz-ms\graphviz2\lib\pathplan\Pathplan.vcproj' cannot be opened because its project type (.vcproj) is not supported by this version of the application. 
 
To open it, please use a version that supports this type of project. 
```
means. That vcproj file says it was created by visual studio 9, I have no idea what the problem is.

**Comment by graphviz** [comment]
This may not be that helpful, but someone claims that you
can run devenv.exe /setup  or regclean and fix some problems.
Others say that doesn’t help.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/484f7c47-a0d9-422b-800c-3a84bfb0d18d/visual-studio-8-vcproj-not-supported-error-message?forum=vcgeneral

Someone claims that you can just use Visual Studio Online (from Microsoft).
http://www.visualstudio.com/en-us/products/what-is-visual-studio-online-vs <http://www.visualstudio.com/en-us/products/what-is-visual-studio-online-vs>

Some people say reinstall Visual Studio, or use "File->New->Project from existing code…”
I think that would mean importing the project files in Visual Studio 2005 (?) and
exporting or saving them in a newer format.

**Comment by tkelman** [comment]
I did try `devenv /setup`, didn't make a difference. I could try `regclean`. We could also contact AppVeyor, they're impressively responsive to support questions.

I haven't tried Visual Studio Online before, but last time I checked it looked like it had a pretty restrictive build time limit. AppVeyor's free plan has a time limit per build, but as long as you only need one concurrent build at a time there's no limit other than the queue time to how many builds you can do total.

Have you been able to sign up for a free account on AppVeyor and enable it?

**Comment by magneticnorth** [comment]
> On Feb 4, 2015, at 4:07 PM, Tony Kelman <notifications@github.com> wrote:
> ...
> Have you been able to sign up for a free account on AppVeyor and enable it?
> 
> 
> 
Just now. Imported graphviz from github. The build failed trivially. I see there’s a learning curve.

**Comment by tkelman** [comment]
I suggest you make an experimental branch for appveyor and add an `appveyor.yml` file, like the one I've started here. You can also configure the build through their GUI but I personally recommend using the yml configuration file instead since it's more discoverable.

**Comment by magneticnorth** [comment]
Thanks. Where is the yml file ?  I didn’t find it in a local copy of graphviz pulled from github.

**Comment by tkelman** [comment]
At the moment, it exists in my fork at https://github.com/tkelman/graphviz/blob/appveyor/appveyor.yml. You need to add it to the top-level folder of the repository. Working in an experimental branch would be good to start with just to avoid making a mess in the history on master.

**Comment by graphviz** [comment]
> On Feb 5, 2015, at 7:40 PM, Tony Kelman <notifications@github.com> wrote:
> 
> At the moment, it exists in my fork at https://github.com/tkelman/graphviz/blob/appveyor/appveyor.yml <https://github.com/tkelman/graphviz/blob/appveyor/appveyor.yml>. You need to add it to the top-level folder of the repository. Working in an experimental branch would be good to start with just to avoid making a mess in the history on master.
> 
> —
> Reply to this email directly or view it on GitHub <https://github.com/ellson/graphviz/pull/37#issuecomment-73160596>.
> 
Thanks. I’m new to this style of development - is the preferred style to make a new branch in the existing graphviz
repository, or make a new repository of my own?  After that, I edit locally, push to github, then ask Appveyor to
rebuild and see what happens? Repeat as needed?
Stephen

**Comment by tkelman** [comment]
I would say make a new branch in the existing repository. You would have to enable AppVeyor separately for a fork under your personal account, but that could work too.

AppVeyor can be configured to build automatically any time anyone pushes to any branch of the repository, or opens a pull request. There is a similar service called Travis CI that can do the same for Linux and OSX, I can show you how to configure that one if there's interest.

**Comment by ellson** [comment]
Stephen,

Your local clone of graphviz is effectively a branch.    For small 
changes I just work in the local clone, commit, compile, test, and then 
only push when I think there is a good chance it will work in the 
nightly builds.    I try to make all changes in small tested increments.

A full branch on the main repo is only needed if you are wanting to 
collaborate on some larger change:    "collaborate"  *AND* "large".

To this point we've never used GIT branches in the main repo.

John

**Comment by tkelman** [comment]
However if you're trying to work on the AppVeyor CI service, which decides when to build based on pushes to github, a full branch here is perfect for testing. Branches in git are really cheap and easy to deal with, it's encouraged to use them for almost everything.

**Comment by graphviz** [comment]
Thanks. I still don’t understand the model.  I added Tony’s appveyor.yml to my
project, and appveyor runs the build, but complains it can’t find FEATURE, GTS,
ann_1.1.2, and eventually grinds to a halt.

Microsoft (R) Visual Studio Version 9.0.30729.1.
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L2996>Copyright (C) Microsoft Corp. All rights reserved.
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L2997> 
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L2998>The following files were specified on the command line:
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L2999> 
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L3000>	c:\graphviz-ms\graphviz2\graphviz.sln
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L3001> 
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L3002>These files could not be found and will not be loaded. 
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L3003>Microsoft (R) Visual Studio Version 9.0.30729.1.
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L3004>Copyright (C) Microsoft Corp. All rights reserved.
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L3005> 
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L3006>The following files were specified on the command line:
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L3007> 
 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6/build/1.0.1#L3008>	c:\graphviz-ms\graphviz2\graphviz.sln

This relates to “running devenv” to set up the environment?
This is done one time, within the Appveyor project and has nothing
to do with the code in github?

https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6 <https://ci.appveyor.com/project/magneticnorth/graphviz-10aa6>

**Comment by ellson** [comment]
Thanks.  Merged.

**Pull request merged**
