### PR TITLE
Fix truncation from 'double' to 'float' warning.

### PR DESCRIPTION
**Pull request by ErwinJanssen**
When compiling with a high warning level on Windows, color_palette.c gives
a warning for every truncation from double to float in this file. Because
of the size of this file, this results in more than 7000 warnings. This
commits fixes this.

### CODE REVIEW

**Comment by emden** [comment]
Does the Window compiler have a flag for turning off that warning? This would be preferable. First, it would avoid the unnecessary doubling of the compiled data. Second, the code in DotIO.c that uses the palettes relies on the data being floats. All of that code would have to be fixed.

**Comment by graphviz** [comment]
Though I can’t remember all the details, wasn’t there a recent patch that just
fixed all the warnings though it touched every line that was involved?
In general I know we agree about fixing warnings instead of disabling them.

**Comment by ErwinJanssen** [comment]
I agree about fixing warnings instead of disabling them. Maybe I could look at how to adjust the code to using doubles.
Another options is to to truncate the values so that they actually fit in a float. Is this a possibility?

**Comment by GadgetSteve** [comment]
Regarding the suggestion from @ErwinJanssen of truncating the values this would not help very much as it is more a compiler default issue that floating point literals are doubles. This could possibly be fixed for a specific compiler with a pragma the "correct" mechanism is to put an f at the end of every value to specify that this is a float rather than a double.

**Comment by GadgetSteve** [comment]
I have raised a pull request Number 1134 with a version of color_palette.c with the **f** suffix approach to addressing the issue for review.

**Comment by ellson** [comment]
I merged Steve Gadget's change instead 
       https://github.com/ellson/graphviz/pull/1134
Thank you both.

**Pull request closed without merging**
