### PR TITLE
Remove unused files

### PR DESCRIPTION
**Pull request by ErwinJanssen**
This pull request is more of suggestion or food for discussion. It's about how clean the repository should be when it comes to unused files.
For me, someone who hasn't worked on this code base for many years, the amount of files that may or may not be used somewhere in the build process is very confusing. To improve the code base, it's often better to remove files and code that are no longer in use. But I do understand the desire to keep previous work and that it's convenient to have reference material.
Would it be an idea to create a new branch called "reference" where a copy of the current state is stored, and to clean the working repository by removing unused files?

### CODE REVIEW

**Comment by ellson** [comment]
There seem to be two major areas here that I think we should decide separately: 

1. remove all Makefile.old (at one time these were maintained to permit building without automake) - AFAIK Emden is/was the only user of this. So Emden should decide. 

2. remove parts of cdt/ that we don't use .. I would be reluctant to do this. It would be much better if libcdt was packaged separately from graphviz altogether and we just added a package dependency to it. I can talk to Adam Edgar about this ... 

John 

----- Original Message -----

**Comment by graphviz** [comment]
Hi - not sure package proliferation is good, though, since I don’t think anyone else uses cdt much.
I think it was important to the AT&T Daytona database - anything else come to mind?

**Comment by emden** [comment]
1. I gave up the old Makefile battle long ago (though we still use one for doc/infosrc), so feel free the remove all of the Makefile.old files.

2. It should be okay to remove the unused subdirectories of cdt. They just provide examples, regression tests, and tsearch/hsearch veneers on top of cdt. (Actually, the most recent version of cdt has also abandoned these.)

I also don't see the advantage of pulling cdt out as a separate package. We could make the case for separating all of the libraries derived from ast (cdt, vmalloc, sfio, expr), and requiring the user to install libast. But that is huge, we only use a small part of it, and we've also modified parts of it, so we can't just use the official version.

Concerning cdt/features/common, I'd suggest keeping it for now. To a large extent, iffe was applied to it to generate the same info that is found in config.h. Given this, at some time we decided to provide a fixed ast_common.h using the #ifdefs from config.h. But if you look inside ast_common.h, there are some values wrapped in FIXME. These are system-dependent but we assume they are constant. We should either figure a way to provide these by configure.ac, or use iffe on features/common to generate them correctly. By the way, I note that running iffe on my current machine, there is different output from what we have in ast_common.h.

**Comment by ErwinJanssen** [comment]
Good call about the Makefile in doc/infosrc, I placed it back and removed the .old extension.

When it comes to `ast_common.h` and `configure.ac`, I think the build could and should be less conditional, especially since we decided to use C99. Some header files are part of C99 (like stdint) and we can assume they are present. So checks like `#ifdef HAVE_STDINT_H` and `#ifdef HAVE_STRING_H` can be removed. In the ideal case, there would only be checks for real platform dependent stuff like specific functions or threads.

About cdt and the other libraries derived from ast: If I understand correctly, the sources included in this repository are part of a larger set of libraries. The sources included here are modified and probably outdated and requiring users to install all of ast is a no go. Either way, dropping these libraries from the repository and using the ast library is no option. Since the sources in this repository are so specific for Graphviz, packaging them separately may not provide a lot of benefits.

So that leaves us with two options I think. Modify these libraries further to suit our needs (remove unused parts, uniform coding conventions, etc.), or remove them all together by rewriting the code that uses these libraries.
I like refactoring, so I wouldn't mind doing any of these options, what do you think?

**Pull request merged**
