### PR TITLE
misc. typos

### PR DESCRIPTION
**Pull request by luzpaz**

### CODE REVIEW

**Comment by ellson** [comment]
Thanks for reading our code so carefully :-)

**Comment by luzpaz** [comment]
@ellson `codespell -d -q 3 --skip="*.po,*.ts"` 😉

**Comment by ellson** [comment]
Arghh! You were just teasng me! There are dozens of other spelling errors dound by codespell!

**Comment by luzpaz** [comment]
@ellson i didn't know which were 3rd party upstream libs

**Comment by ellson** [comment]
Anything in the github graphviz tree, we will maintain.

I've just fixed a lot more spelling errors detected by codespell. There may be more...

**Pull request merged**
