### PR TITLE
Start of new cross platform regression tests with Python

### PR DESCRIPTION
**Pull request by ErwinJanssen**
The current regression tests only run on Unix and the reference files aren't up to date. In this pull request I propose a new way to perform the regression tests: using Python. With Python, the tests can be executed on any platform, so the Windows binaries can be tested as well.
Currently the only the different shapes are tested and only with `.gv` output, but I thought it would be a good idea to submit this before spending more time on it.

The reason that I only includes the `.gv` output, is that other output formats produced slightly different results on the different platform. These differences were mostly in the floating point positions of some shapes. It would be best if these differences could be eliminated, where are the exact coordinates of the various shapes determined?

### CODE REVIEW

**Comment by ellson** [comment]
Shape generation is in lib/common/shapes.c

The shapes are sized to fit around labels,   so any variation in fonts on different platforms can have an effect on the layout.    Maybe we should include a font just for regression testing?

**Comment by ErwinJanssen** [comment]
These regression tests are for shapes without labels, and the differences are very subtle. For example, (part of) the SVG output for the shape "diamond" on Windows:

```
<g id="node1" class="node">
<title>a</title>
<polygon fill="none" stroke="#000000" points="27,-36 0,-18 27,-3.55271e-15 54,-18 27,-36"/>
</g>
```
And on Linux:
```
<g id="node1" class="node">
<title>a</title>
<polygon fill="none" stroke="#000000" points="27,-36 3.55271e-15,-18 27,-3.55271e-15 54,-18 27,-36"/>
</g>
```

All differences in the regression test results are with coordinates that are (close to) zero. Most of them, like the example above, are with one platform setting a coordinate to zero, the other to a value very close to zero (`3.55271e-15`). The rest is one platform setting the coordinate to zero, the other to negative zero.

I think it has something to to with orientation attribute of the shapes, but I couldn't find where the exact coordinates of the shapes are calculated. Adding an edge case for values close to zero should solve it.

**Comment by emden** [comment]
Testing has always been a bane for us. As far as I can tell, comparing two images has not been solved yet, at least, Google hasn't. Except when the layout fails or there are really egregious differences, you basically have to compare the two images visually. On the other hand, I suspect the solution is not too far away, given the massive amount of work on facial and pattern recognition and the recent advances in AI.

The only hope of some automation was to have separate test data for each machine/OS/version. This usually boiled down to picking one of our machines and only testing on that.

The coordinates for polygonal shapes are generated in lib/common/shapes.c, starting at line 2122, right after the FIXME comment:

        vertices = N_NEW(outp * sides, pointf);
        if (ND_shape(n)->polygon->vertices) {
            poly_desc_t* pd = (poly_desc_t*)ND_shape(n)->polygon->vertices;
            pd->vertex_gen (vertices, &bb);
            xmax = bb.x/2;
            ymax = bb.y/2;
        } else {
            sectorangle = 2. * M_PI / sides;
            sidelength = sin(sectorangle / 2.);
            skewdist = hypot(fabs(distortion) + fabs(skew), 1.);
            gdistortion = distortion * SQRT2 / cos(sectorangle / 2.);
            gskew = skew / 2.;
            angle = (sectorangle - M_PI) / 2.;
            sincos(angle, &sinx, &cosx);
            R.x = .5 * cosx;
            R.y = .5 * sinx;
            xmax = ymax = 0.;
            angle += (M_PI - sectorangle) / 2.;
            for (i = 0; i < sides; i++) {
etc.
Given floating point arithmetic is involved, it is not surprising that subtle differences occur.

**Comment by ErwinJanssen** [comment]
Visually comparing two images is tricky, but, you created the diffimg utility to solve this problem, right? It's easier with text based output such as gv and SVG, so I started with that first. 

I hope to create some tests that run equally on all platforms, but sometimes this will require changes in the code. I found the location where the coordinates are calculated are added a check for near zero cases. This allowed the regression test to include the SVG and xdot output types (and probably other text based output types). The tests succeed on all platforms I have tested them on: Windows, Debian, Appveyor and Travis.

**Comment by magneticnorth** [comment]
Yes, agree. Various sources claim to have useful software for computing
“perceptual differences” but it would take some work to figure out if they
are suitable for us.  I don’t know any that deal with possible issues like 
offsets due to different margins or maybe parts of the layout shifted.
http://pdiff.sourceforge.net <http://pdiff.sourceforge.net/>

imagemagick has a powerful image compare utility, and maybe some way
to cough up a metric that reflects the number of pixels that changed.
http://www.imagemagick.org/Usage/compare/ <http://www.imagemagick.org/Usage/compare/>

Sorry not to add more useful information but maybe someone else can help.

**Comment by ellson** [comment]
Emden, Erwin,

Is this  ready for merging?     If its additional and doesn't affect Emden's current regressions tests, then I'll merge.   Can you please confirm,?

**Comment by ErwinJanssen** [comment]
These tests are additional and to not influence the current regression tests in any way. They are included in the `make check` step, but if the additional comparisons are added, this step succeeds.

You raise a good point about the additional comparisons performance, I did not check that before sending this PR. To test this I executed `time ./rtest.sh` 15 times with the code before the change and 15 times after. Results in the tables below:

__Before the additional comparisons__

| real time | user time | system time |
| -------- | ---------- | ------- |
| 17.277 | 11.748 | 0.380 |
| 18.284 | 11.868 | 0.648 |
| 17.610 | 11.672 | 0.340 |
| 17.934 | 11.740 | 0.392 |
| 17.774 | 11.736 | 0.404 |
| 17.416 | 11.644 | 0.344 |
| 17.873 | 11.764 | 0.392 |
| 18.161 | 11.788 | 0.380 |
| 17.473 | 11.536 | 0.316 |
| 17.879 | 11.768 | 0.412 |
| 18.112 | 11.716 | 0.456 |
| 17.845 | 11.808 | 0.408 |
| 17.618 | 11.596 | 0.424 |
| 18.114 | 11.872 | 0.348 |
| 17.379 | 11.444 | 0.420 |
| __Averages__  |
| 17.783 | 11.713 | 0.404 |

__After the additional comparisons__

| real time | user time | system time |
| -------- | ---------- | ------- |
| 17.269 | 11.440 | 0.436 |
| 17.813 | 11.844 | 0.408 |
| 17.721 | 11.616 | 0.404 |
| 17.520 | 11.624 | 0.360 |
| 17.574 | 11.540 | 0.432 |
| 17.644 | 11.680 | 0.372 |
| 17.578 | 11.592 | 0.380 |
| 17.612 | 11.612 | 0.408 |
| 17.670 | 11.640 | 0.404 |
| 17.873 | 11.696 | 0.384 |
| 17.238 | 11.428 | 0.400 |
| 17.597 | 11.776 | 0.364 |
| 17.318 | 11.544 | 0.408 |
| 17.405 | 11.588 | 0.400 |
| 17.579 | 11.660 | 0.416 |
| __Averages__  |
| 17.561 | 11.619 | 0.398 |

Looking at this benchmark, I don't see a performance impact.

I'm not sure what you mean with "clamping", could you elaborate?

**Comment by emden** [comment]
As an aside, I hope to clean up the last of the regressions this weekend, so we should be able to cut a new release next week.

**Comment by ellson** [comment]
I'm calling the effect of your comparisons "clamping"


You are "clamping" numbers  with magnitude < 10**-5 pixels to exactly zero.


BTW, we already have something like this in lib/gvc/gvdevice.c:gvprintnum()

which is use to keep the string representation of numbers in SVG and PS to a reasonable length.


Which raises the issue of where are you seeing these very small numbers - is it in -Tdot or -Txdot output ?


The noise in very small numbers isn't big enough to affect bitmap images ...  and I think I already

took care of the same issue in SVG and PS output.


So, if the issue is in -Tdot, or -Txdot output, then I think the "clamping" should be taken care of in the

number representation on the output.     


Changes to the shape() code are probably unnecessary, and make me nervous given the time i spent getting that code to work in a stable fashion in the first place.


John

**Comment by ellson** [comment]
I merged everything except for "Fix: shape coordinates close to 0 now absolutely 0"

**Comment by ellson** [comment]
I modified the svg renderer to use my number string rounding code (PS and TK were already using it).      I updated the regression references to accept the new output.

( I wish there was a way to write a custom % formatter for printf()   ??)

I did not add my code to the xdot output.  I updated the reference files for  those two xdot test cases to match what is currently generated  -- it includes some "-0" values.

Erwin's regression tests are run in the Travis CI builds,  so the builds fail if these regression tests fail.

**Pull request merged**
