### PR TITLE
Beginning of CMake build

### PR DESCRIPTION
**Pull request by ErwinJanssen**
This pull request adds CMake build and configuration files, no changes to the original Autotools build were made. The recommended way to build this is to perform an out of source build, like so:

```Shell
mkdir build # Directory for out of source build
cd build
cmake .. # Generate default build files (make for Linux, Visual Studio for Windows)
cmake --build . # Perform the build (runs make on Linux)
```
This build is also included in the Appveyor and Travis build.
Only part of the libraries are build with this configuration. The rest will be added but I wanted to show the progress. The flowing libraries are included now:
- cdt
- cgraph
- circogen
- dotgen
- fdpgen
- ingraphs
- label
- neatogen
- ortho
- osage
- pack
- patchwork
- pathplan
- rbtree
- sparse
- sfdpgen
- spine
- twopigen
- vmalloc
- vpsc
- xdot

### CODE REVIEW

**Comment by ellson** [comment]
Looking good.   Are you expecting any issues with building plugins?

**Comment by ErwinJanssen** [comment]
I haven't look closely at that yet, so I'm not sure. Mostly the Windows part is being problematic, in the current build various pregenerated files are used, but I would like to eliminate this in the CMake build. For example, Perl is used in lib/common, but Perl is not available on Windows on default. Requiring the user to manually install it involves additional manual configuration (which we don't want) and including a portable Perl package in the build tools submodule increases the size with more than 100MB (which we don't want either).

**Comment by ellson** [comment]
> For example, Perl is used in lib/common, but Perl is not available on Windows on default.

Its used by mksvgfonts.pl to generate ps_font_equiv.h. I'm sure this could be rewritten to some
combination of: bash, sed. awk does Windows have those? How about tclsh?

**Comment by ErwinJanssen** [comment]
Windows does have awk and sed, but no bash or tclsh. Maybe Python is an option? Almost all systems have that installed.
On the other hand, the input files of various generated files (like `ps_font_equiv.h`) rarely change. Is it an option to keep a generated version and remove this build step?

**Comment by GadgetSteve** [comment]
Just for clarity python is **available** for windows but **not** installed by default, _unfortunately_. Windows 10 _**can**_ now have a bash shell for Ubuntu installed that includes awk, sed, tclsh & python but given that it is not available for older versions of Windows I would say going with python and making it a prerequisite of the build chain would be the best idea since the remainder of the build tools will have to be found by a developer in any case.

**Comment by magneticnorth** [comment]
I would think Powershell regex expression substitution FTW.

**Comment by ellson** [comment]
Maybe you could try,  Pythin is too new-fangled for me ... I like tools that have been around a long time that we could reasonably expect to be on all platforms,  or at least on all build machines of all platforms.


(Sorry,  frustration is starting to show...)

**Comment by ellson** [comment]
>> On the other hand, the input files of various generated files (like ps_font_equiv.h) rarely change. Is it an option

>> to keep a generated version and remove this build step?


I really dislike the idea of storing any build products in a repository.   I think it makes the repository unclean,  bloated, and subject to unnecessary changes.


Either a platform supports *all* the tools needed to build from source,  or it should use the provided graphviz.tar.gz



Even for Windows -- whats the objection to installing perl on the *build* machines?     Its not required on the final install machines.


John

**Comment by ellson** [comment]
So why not go back to the two stage process for building from source:


    1.  Generate a platform agnostic graphviz.tar.gz  on one machine that has all the tools for generating the interim products:

       autgoconf, automake, swig, yacc, lex, .... bash



    2.  Generate binary products on each platform only from the graphviz.tar.gz distribution.



John

**Comment by ErwinJanssen** [comment]
I agree a platform should support *all* the tools needed to build from source. And you have a point when you say that the additional tools are only required for the build. On top of that, Perl is also available for Windows. I prefer this above the two stage process, so I will continue to expand the CMake build to support the current build steps.

**Comment by emden** [comment]
If a build from git works, great, but building from the current source package avoids the need for extra tools while still staying current. The worst part of the old regime was having to keep the project files up to date, as opposed to having them generated from the Linux makefiles.

**Comment by magneticnorth** [comment]
FYI/FYA  on OSX this mostly succeeds, except vmalloc (do we still use that?) has some
difficulty with not knowing that it needs sys/types.h so it can get the definition of ssize_t

**Comment by emden** [comment]
vmalloc is crucial for gvpr.

**Pull request merged**
