### PR TITLE
Use gvc.def for exported symbols with MinGW build

### PR DESCRIPTION
**Pull request by tkelman**
A few of the libtool symbols needed to be removed (deprecated, apparently) otherwise I would get
```
Cannot export lt_dlcaller_register: symbol not defined
Cannot export lt_dlforeach: symbol not defined
Cannot export lt_dlhandle_next: symbol not defined
Cannot export lt_dlloader_data: symbol not defined
Cannot export lt_dlloader_name: symbol not defined
Cannot export lt_dlmutex_register: symbol not defined
collect2: error: ld returned 1 exit status
make[3]: *** [libgvc.la] Error 1
```

And I needed to add `orthoEdges` to the list otherwise I would get
```
../../lib/dotgen/.libs/libdotgen_C.a(dotsplines.o):dotsplines.c:(.text+0x8c5): undefined reference to `orthoEdges'
../../lib/dotgen/.libs/libdotgen_C.a(dotsplines.o):dotsplines.c:(.text+0x8db): undefined reference to `orthoEdges'
/usr/bin/x86_64-w64-mingw32-ld: ../../lib/dotgen/.libs/libdotgen_C.a(dotsplines.o): bad reloc address 0x0 in section `.data'
collect2: error: ld returned 1 exit status
make[3]: *** [libgvplugin_dot_layout.la] Error 1
```

For reference, I'm currently configuring as `../configure --host=x86_64-w64-mingw32 CFLAGS="-DPATHPLAN_EXPORTS -D_DLL -DGVC_EXPORTS -DVMALLOC_EXPORTS" --without-gtk` in a cross-compile from Ubuntu 14.04 (Cygwin-to-MinGW-cross or MSYS should work similarly) and getting through all of `lib`, currently hitting
```
../../../cmd/dot/dot.c: In function ‘main’:
../../../cmd/dot/dot.c:158:28: error: ‘lt_preloaded_symbols’ undeclared (first use in this function)
     Gvc = gvContextPlugins(lt_preloaded_symbols, DEMAND_LOADING);
                            ^
../../../cmd/dot/dot.c:158:28: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [dot-dot.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/dot_builtins-dot_builtins.Tpo .deps/dot_builtins-dot_builtins.Po
mv -f .deps/dot-no_builtins.Tpo .deps/dot-no_builtins.Po
../../../cmd/dot/dot.c: In function ‘main’:
../../../cmd/dot/dot.c:158:28: error: ‘lt_preloaded_symbols’ undeclared (first use in this function)
     Gvc = gvContextPlugins(lt_preloaded_symbols, DEMAND_LOADING);
                            ^
../../../cmd/dot/dot.c:158:28: note: each undeclared identifier is reported only once for each function it appears in
make[3]: *** [dot_builtins-dot.o] Error 1
```

Will see if I can resolve that one.

### CODE REVIEW

**Comment by tkelman** [comment]
I found a way to resolve the issue with `lt_preloaded_symbols` in dot (it will need to be reviewed though), and got a bit further. lefty is having trouble:
```
In file included from /usr/share/mingw-w64/include/sys/stat.h:14:0,
                 from ../../../../../cmd/lefty/common.h:53,
                 from ../../../../../cmd/lefty/ws/mswin32/garray.c:16:
../../../../../cmd/lefty/io.h:37:5: error: unknown type name 'FILE'
     FILE *ifp, *ofp;
     ^
In file included from /usr/share/mingw-w64/include/sys/stat.h:14:0,
                 from ../../../../../cmd/lefty/common.h:53,
                 from ../../../../../cmd/lefty/ws/mswin32/gbutton.c:16:
../../../../../cmd/lefty/io.h:37:5: error: unknown type name 'FILE'
     FILE *ifp, *ofp;
     ^
In file included from /usr/share/mingw-w64/include/sys/stat.h:14:0,
                 from ../../../../../cmd/lefty/common.h:53,
                 from ../../../../../cmd/lefty/ws/mswin32/gcanvas.c:16:
../../../../../cmd/lefty/io.h:37:5: error: unknown type name 'FILE'
     FILE *ifp, *ofp;
     ^
In file included from /usr/share/mingw-w64/include/sys/stat.h:14:0,
                 from ../../../../../cmd/lefty/common.h:53,
                 from ../../../../../cmd/lefty/ws/mswin32/gcommon.c:16:
../../../../../cmd/lefty/io.h:37:5: error: unknown type name 'FILE'
     FILE *ifp, *ofp;
     ^
```

I think what's happening here is mingw's `stat.h` is getting confused by lefty's copy of `io.h`. Would anyone mind terribly if I renamed `cmd/lefty/io.h` to `cmd/lefty/leftyio.h`, or something equivalent? Along with renaming these occurrences of it of course:
```
cmd/lefty/dot2l/dot2l.c:16:#include "io.h"
cmd/lefty/dot2l/dotlex.c:20:#include "io.h"
cmd/lefty/lefty.c:26:#include "io.h"
cmd/lefty/gfxview.c:19:#include "io.h"
cmd/lefty/Makefile.am:49:       io.h lex.h mem.h parse.h str.h tbl.h txtview.h
cmd/lefty/os/unix/io.c:17:#include "io.h"
cmd/lefty/os/mswin32/lefty.mak:432:     ".\io.h"\
cmd/lefty/os/mswin32/lefty.mak:463:     ".\io.h"\
cmd/lefty/os/mswin32/lefty.mak:490:     ".\io.h"\
cmd/lefty/os/mswin32/lefty.mak:617:     ".\io.h"\
cmd/lefty/os/mswin32/lefty.mak:635:     ".\io.h"\
cmd/lefty/os/mswin32/lefty.mak:654:     ".\io.h"\
cmd/lefty/os/mswin32/io.c:18:#include "io.h"
cmd/lefty/internal.c:19:#include "io.h"
```

**Comment by tkelman** [comment]
And it now builds! This of course needs proper testing, but at the very least this branch can finish compiling with the following:
```
../configure --host=x86_64-w64-mingw32 --prefix=$PWD/usr CFLAGS="-DPATHPLAN_EXPORTS -D_DLL -DGVC_EXPORTS -DVMALLOC_EXPORTS -DLAB_GAMUT_EXPORTS -D_BLD_gvc -DGVDLL" --without-gtk --without-pangocairo --without-qt && make -j4
```

**Comment by magneticnorth** [comment]
Hi Tony.  That’s impressive.  

We perhaps don’t need Lefty, it’s quite an old program. I am not sure to what
extent any legacy applications in Windows would need it.

We probably do need Cairopango (some new rendering features depend on it)
and we probably want gtk so we can support the new GUI.  What are your
thoughts about the difficulty of this?  

Stephen North

**Comment by tkelman** [comment]
Hi Stephen. The only issue with Cairo and GTK is that cross-compiled Windows (MinGW) versions of them are not available in Ubuntu, or Debian, or Cygwin. However they are available in Fedora, openSUSE, Arch, or MSYS2. So I think I'd have to switch my build environment, or use a Vagrant VM or Docker container to try a different distribution (most likely openSUSE, since they have a great build service that you can use to automatically build and package binaries once everything is working) to cross-compile from.

**Comment by graphviz** [comment]
Hi - what else needs to be done to move the Windows build to Appveyor?
I think we definitely need cairo/pango for some of the new rendering features,
and need gtk to build gvedit.
Stephen North  north@graphviz.org <mailto:north@graphviz.org>

**Comment by tkelman** [comment]
On AppVeyor, with an autotools-MinGW build, the best bet would be figuring out how to install MSYS2 and their MinGW binaries of cairo and gtk.

**Pull request merged**
