### PR TITLE
Cleanup and pruning

### PR DESCRIPTION
**Pull request by ErwinJanssen**
A collection of changes that clean up and improve parts of the repository. Various changes affect `lib/sfio/features/sfio` by (re)moving checks from this file. This enables cleaner checks and help to implement the CMake build for `lib/sfio`.

### CODE REVIEW

**Comment by magneticnorth** [comment]
> 
> Removed two unused checks from features/sfio
> Replace _hdr_stat with HAVE_STAT_H
> Move two checks from features/sfio into the code
> Move type checks features/sfio to configure.ac
> Remove lib/sfio/features/stdio
> Update macro checks in lib/sfio

SFIO is Phong Vo’s Safe Fast I/O library, from AT&T Labs about 15 years ago.
He’s at Google now, and the SFIO page at AT&T doesn’t work any more.
There’s an empty page at https://github.com/att/sfio <https://github.com/att/sfio>.  (… is paved with good intentions?)

Anyway, we should be a little careful about changing the code for cleanup if it
will make it harder to get Phong or anyone else to help with it in the future.

On the other hand, maybe Graphviz effectively owns sfio now?  That would be funny.

**Comment by ErwinJanssen** [comment]
There is also the AT&T AST repository, which contains the source of `ast`, `cdt`, `sfio`, `vmalloc`, etc: https://github.com/att/ast/tree/master/src/lib/libast

I agree that we should be careful about changing this code, especially because we do not have a lot of tests. However, in it's current form `sfio` is more difficult to maintain, especially on Windows where the checks from `features/sfio` can't be used.

As far as I am aware, Graphviz does not distribute SFIO, but statically links it to some parts like `smyrna`. Is that correct?

**Comment by emden** [comment]
The gvpr filter relies on libexpr from libast, which in turn uses vmalloc, sfio and ast. These are actually fairly old versions and not necessarily complete, especially ast. Graphviz distributes sfio in the sense that it is part of the source tree. I don't think Phong plans to get involved with sfio or vmalloc anymore. Lefty is probably the curator of the code.

**Comment by ErwinJanssen** [comment]
All of the changes in sfio are limited to the feature checks prior to compilation, no other changes were intended. I also noticed a lot of the changes in this PR consist of white space trimmed by my editor, so the amount of actual changes is less than it might seem.

**Comment by ellson** [comment]
We need a decision on how to proceed here.

I think we should accept that our SFIO is going to be our own fork from the original (propably already is)  and that we should maintain it consistent with the rest of the graphviz code.   Its not like we invite or facilitate using SFIO outside of graphviz.

Should we ever want to merge or switch to an external "official" SFIO,  well,  we may need some work,  but we have all the history of our changes in GIT.

I vote to merge this change.

**Comment by magneticnorth** [comment]
OK. I agree that no one else seems to be maintaining sfio.

**Pull request merged**
