### PR TITLE
CMake fixes (make compile; add graphviz_version.h)

### PR DESCRIPTION
**Pull request by krf**

### CODE REVIEW

**Comment by krf** [comment]
@ErwinJanssen Please have a look.

**Comment by ErwinJanssen** [comment]
Looks good to me! The `FeatureSummary` is a neat addition, I didn't know that existed.

The failing build is caused by the Visual Studio project of `tred`, which is not yet linked to `lib\common`, but that's not a CMake issue so this this PR can be merged.

**Comment by krf** [comment]
Regarding the issue with `tred`: That's what https://github.com/ellson/graphviz/pull/1247/commits/8f1d301620a51e743da684ddc49cf8af28aa4890 is supposed to fix, no?

**Comment by ErwinJanssen** [comment]
That fixes it for the CMake build, the Visual Studio build (which we are going to replace with the CMake build) has to be modified separately.

**Comment by ellson** [comment]
merged.

> Regarding the issue with tred: That's what 8f1d301 is supposed to fix, no?

Maybe.  It fixed a problem where timing.h was not getting included in the tar.gz sources,  which in turn did fix the Linux rpm builds.

**Pull request merged**
