### PR TITLE
Windows build

### PR DESCRIPTION
**Pull request by ErwinJanssen**
This pull request contains a working build for Windows and an Appveyor script. The build is successful, but the resulting binary package is not complete yet. Some DLLs on which Graphviz is depended should be included along with the header files, etc. This is something I could work on later if this is appreciated.

Some dependencies were required, like GTK and expat. These had to included on Appveyor, but were not all easy to find or had no automated installation for Appveyor. I included those dependencies as Git submodules.

Getting the build to work is done solely through configuration files and defines, no actual changes in the code were made.

### CODE REVIEW

**Comment by magneticnorth** [comment]
I’m thrilled and amazed to see this. Also congratulations on getting it to work without changing the
code (assuming the defines are pretty benign).  We will need to get this merged in and running for
everyone to benefit, so need to coordinate with Emden and John.
Stephen

**Comment by ErwinJanssen** [comment]
Thank you for your kind words @magneticnorth. Is there something I can do to help, or will you coordinate with Emden and John?

Hopefully this also helps in solving the licence issue #82.

**Comment by graphviz** [comment]
Hi - note that to satisfy Eclipse, we’re attempting to get rid of 
lib/gvc/regex_win32.c and lib/gvc/regex_win32.h and there
is now a replacement under lib/rxspencer
Not sure if it compiles and links under Windows easily but
it seems like that would be the goal.
Stephen

**Comment by ErwinJanssen** [comment]
I removed win32_regex and added rxspencer to the Windows build. Instead of compiling rxspencer on Windows, I included precompiled win32 development libraries as a submodule, linking went smooth.

**Comment by ErwinJanssen** [comment]
I just noticed that merging the upstream to windows-build, causes the build to fail. I shall investigate what caused this. Right now Appveyor fails.

**Comment by ellson** [comment]
I had to fix the breakage to the "make dist" target cause by the .vcprog ->.vcxprof changes

I noticed that there is no cmd/tools/gv2gxl.vcxproj,  is that OK?

**Comment by ellson** [comment]
Are you saying that Windows does *not* use rxspencer?   Its not used on Linux, so if you don't need it for Windows i can remove rxpencer entirely.

While I'm deleting stuff,  I see we still have an old, unpatched, copy of libgd in the GIT repo.  I'd like to completely remove that too.   Do you use libgd on Windows?  If sio, do you included it as a submodule(>) separate from graphviz sources?

**Comment by ErwinJanssen** [comment]
I pinpointed the problem and will have solved it tomorrow.
The Windows build doesn't use the rxspencer code included in the repository. It uses precompiled libraries that are added as a submodule.
The project in lib/gd is included in the Windows build. Are you saying it should be removed / updated / included as a submodule? What does this library do?

**Comment by ellson** [comment]
Erwin,

I think I already fixed the build breakage - at least for Linux (broken 
"make dist" due to .vcxproj files).

Thanks for confirming rxspencer is not used,  I will remove it now.

i will leave gd for a while, but I would really like to remove that too.

lib/gd is an old copy of the source of the "gd" graphics library 
(variously known as libgd, or gdlib).   Its quite dated now and 
pango/cairo is much better.

For the Linux builds we still support gd, but we link to the shared lib 
from a separately installed package, eg, for Fedora:

     gd-2.1.1-6.fc23.x86_64

     gd-devel-2.1.1-6.fc23.x86_64

If you still use it for Windows builds then you should use external 
sources.  I don't keep the gd sources up to date with the various 
security fixes I see going into the official version, which I think is at:

      https://github.com/libgd

John

**Comment by ErwinJanssen** [comment]
The Windows build was still broken, but PR #1135 fixes this.

I shall see what I can do about gd. You mention it's outdated and pango/cairo is much better, how long should gd be supported?

**Comment by ellson** [comment]
Erwin,

#1135 has been merged.


I think we should continue supporting gd renderer,   I just don't want 
to use an in-tree stale copy of gd to do it.   I don't want any 
responsibility for maintaining base gd library code.

(Specifically,  I want to "git rm -r lib/gd", but keep plugin/gd )

Can't you get it from a dll provided by them?   I don't know how package 
dependencies are managed on Windows,

Or, can you import it as a submodule from their github repo?

John

**Comment by ErwinJanssen** [comment]
I replaced the stale in-tree version of libgd with a build of the most recent version of the code. See #1137 for details.

**Comment by graphviz** [comment]
Hi - how can we try the Appveyor build or at least the build product?
Does it also deal with packaging or creating an installer?
How should this get integrated into the rest of graphviz within github?
Stephen

**Comment by ErwinJanssen** [comment]
Activating the Appveyor build is quite straightforward and similar to the setup of Travis. You log in in [appveyor.com](http://www.appveyor.com/) using your Github account and add Graphviz as a project. It should build on the next commit. I think John should do this since he owns the ellson account where this repository is hosted.

At the moment the build is automated, so it can be verified if changes don't break the Windows build. Appveyor creates a hook to Github so all pull requests are checked when they are created, same as Travis.

For a usable package I must first fix some dependencies and script the copying of some DLLs. I have no experience creating an installer, but would be willing to investigate this if someone could provide me with tips.

**Comment by ellson** [comment]
I've added appveyor to my ellson account on github.

**Comment by ellson** [comment]
Do I have to configure something extra to get the Appveyor products listed on the GitHub page,  like the way Travis products are reachable from "Releases" ?

**Comment by ErwinJanssen** [comment]
Yes extra configuration is required, but I shall get to this soon. There are some small changes to make before a usable package can be released.

**Comment by ErwinJanssen** [comment]
John,

Some of the changes you have made to the `.travis.yml` configuration file result in Travis not publishing any releases. With the current configuration, the follow happens:

When a commit is made to ellson/graphviz, Travis is triggered to perform an automated build and checks whether it will deploy a release. A release is made if all conditions listed below `deploy: on:` are satisfied. Right now, the only condition is that the commit is made to `ellson/graphviz`, which is always the case when committing to this repository. This means that a deploy is triggered on every commit. Because the deploy isn't triggered by a git tag, Travis creates its own tag, with names like `untagged-dca5f3fa2a3476aaf8e3: Merge pull request #1137 from ErwinJanssen/replace-libgd`. These names aren't proper version numbers or release names, and because they are created on every commit, the release page in Github gets quite cluttered. Preferably, Travis should perform an automated build on every commit, but only release when a git tag is pushed. This results in a fewer releases and better defined release names. This can be added by adding `tag: true` to the deploy section.

```
deploy:
  on:
    tag: true
```

When a release is made using the current configuration, __nothing actually gets deployed__ to Github Releases. The two links in the download section of every release (`Source code (zip)` and `Source code (tar.gz)`) are download links to a snapshot of the repository on Github at the time of the commit, these are automatically created by Github on every tag. Neither the results from `make dist` or the results or `make install` get deployed to Github. This is because the specification of which file to deploy is removed. To deploy a file on a release, you must specify which file to deploy and tell Travis not to clean up after the build.

```
deploy:
  skip_cleanup: true
  file: <file to deploy>
```

So for a successful release on a git tag, the deploy section should look like this:

```
deploy:
  provider: releases
  api_key:
    secure: <secure api key>
  file: <file to deploy>
  skip_cleanup: true
  on:
    repo: ellson/graphviz
    tag: true
```

The products should be usable binaries, or install packages, as a snapshot of the source code is already automatically included. But what binaries should be deployed? I found out that the package I created for deployment, the results from `make install` can not find the configuration and `dot -c` has no effect. Maybe this is because of the `--prefix` path I used to create the package is not the same as the path were the package is saved after downloading it from Github? Or some environment variable must be set first? How should this be done?
Also I'm not familiar with creating rmp or deb packages, what are the steps to do this?

Ideally to me (and please correct me if I you see this differently), Travis (and also Appveyor in the near future) should only deploy a release to Github when a release is marked with a git tag to indicate the release version.
Right now Graphviz is on version 2.39 and the even-odd versioning is used, which leads to long release times. If I understood correctly, this version has been in development for over two years, and some critical patches are not available for those still using 2.38. A lot of projects use [Semantic Versioning](http://semver.org/), which include a third "patch" number to indicate small changes that don't bring new functionality. The link points to a website that gives a quick overview of semantic versioning, which might be useful.

Erwin

**Comment by ellson** [comment]
Erwin,

What I would like is:

     - the travis build to generate the "make dist" graphviz*.tar.gz 
that I use as the basis for all Linux binary package builds.

     - publish that file somewhere accessible over the web - each one is 
uniquely named,   but I only need the most recent to be kept and visible.

     - the traviz build to complete a build of the binaries on one 
distro/os/architecture (doesn't matter much which) and indicate if there 
are any problems.  - as it does now.

     - I don't have a use for this binary image, other than to know that 
the compile succeeded.

     - I would prefer to only tag stable releases (ideally one-per-month 
or so)   but i want to continue building nightly snapshots,  and I would 
like to base these on the last "make dist"  tar.gz package.


Can you help me set this up?    The .travis.yml is in the tree.


John

**Pull request merged**
