### PR TITLE
Various changes

### PR DESCRIPTION
**Pull request by ErwinJanssen**
Various changes which decrease the amount of (redundant) defines, removes unused code, etc. These changes should not have any effect on the functional properties of the code, but should reduce the complexity of the whole.
To test the impact of these changes I ran the regression tests before and after the changes, the regression tests had the same results.

### CODE REVIEW

**Comment by magneticnorth** [comment]
Hi - we can't thank you enough for the work on this, especially getting an Appveyor build set up.

Regarding cdt, we just need to think through changes we make that will diverge from the current code in case there are updates. Unfortunately, I don't know if it's being maintained by Phong Vo.  I believe it is very important to the database that underlies a large network application in AT&T, but most of the inventors of that technology are not working there any more, so it's not clear who's in charge of the code base.  On the other hand, it's good news that cdt has been very stable and there has been little need for any updates.

Best regards,
Stephen North

**Comment by emden** [comment]
As far as I can tell, all of ast has been frozen since 2012. Lefty "maintain" a copy on github, which I believe is the latest. Stephen synced our cdt with the latest ast in 2010, but there have been a few changes since then. One reason for keeping the "unused" code is that it is easier when we need to compare what has changed in new versions. Since there probably aren't going to be any new versions, I'd  recommend updating our cdt with the one on github, and then stripping out the dead code.

One reason for updating is the newest ast has better thread-safe code. In particular, I am in the process of bringing in the new vmalloc, because smyrna uses gtk+ which uses threads that cause smyrna to crash. Even though we have noted that Graphviz is not thread safe, that may not be enough. Newer libraries may use threaded code that can break things.

**Comment by magneticnorth** [comment]
Good points. I would hope that someday, if there is new work on this code,
we might want to look into multithreaded solvers for various layout phases.
It would be fun to work on.

**Comment by ErwinJanssen** [comment]
Thank you for your feedback, I removed the commits that removed unused code from CDT from this pull request. What is the location/repository of the official version of CDT? 

I also added the new library spine which was added by @emden to the Visual Studio build.

**Comment by emden** [comment]
Thanks for handling the Windows build for spine.

The newest version of the cdt library (and all of ast) is at https://github.com/att/ast.

**Pull request merged**
